### ISSUE TITLE
Unable to open workspace with stored diagrams

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#376]
I cannot open https://xn--slovnk-7va.gov.cz/modelujeme/workspace/instance1935230504 in OG. The console says that there is an unrecognized term https://slovník.gov.cz/generický/veřejná-místa/pojem/vlastník-jako-právnická-osoba . However, this terms exists in the model and is available. Maybe again some residuum from the past?

**Comment by martinnec** [comment]
Another example of a workspace which I cannot open

https://xn--slovnk-7va.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1149081494

I will try to summarize what I did:
- I removed several item from the model.
- A created a new item.

What happened:
- Many unrelated items appeared in the diagram as <blank>. They were not only visualized in the diagram - they were part of the model as they appeared on the left hand side list of model items.
- The new item was in the diagram but it was on the left hand side list of model items.
- I refreshed OG (F5) but it did not load anymore.

In the console I can see:

```
FunctionCreateVars.ts:73 Uncaught (in promise) Error: IRI https://slovník.gov.cz/generický/věci/pojem/má-autora-díla not recognized as a term in the workspace.
    at ca (main.25dcecbd.chunk.js:1:99750)
    at main.25dcecbd.chunk.js:1:233364
    at l (2.44db1f78.chunk.js:2:1424287)
    at Generator._invoke (2.44db1f78.chunk.js:2:1424075)
    at Generator.next (2.44db1f78.chunk.js:2:1424716)
    at r (2.44db1f78.chunk.js:2:181909)
```
